In [20]:
## Factor
fact1 <- factor(c("a","b","c","c","a","b"))
fact1
str(fact1)
fact2 <-factor(c("a","b","c","c","a","b"),labels=c(1,2,3),levels=c("c","a","b"))
fact2
str(fact2)

[1] a b c c a b
Levels: a b c

 Factor w/ 3 levels "a","b","c": 1 2 3 3 1 2


[1] 2 3 1 1 2 3
Levels: 1 2 3

 Factor w/ 3 levels "1","2","3": 2 3 1 1 2 3


In [21]:
## Matrix
## Numeric Matrix
mat1 <- matrix(1:10,nrow=5)

## Categorical Matrix
mat2 <- matrix(c("ID","Total",1,10,2,45,3,26,4,8),ncol=2,byrow=T)

In [22]:
mat1

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [23]:
mode(mat1)

[1] "numeric"

In [24]:
mat2

[,1] [,2] 
[1,] ID   Total
[2,] 1    10   
[3,] 2    45   
[4,] 3    26   
[5,] 4    8

In [25]:
mode(mat2)

[1] "character"

In [26]:
## Array
arr1 <- array(1:18,c(3,2,3)) 
arr1

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

, , 3

     [,1] [,2]
[1,]   13   16
[2,]   14   17
[3,]   15   18

In [27]:
##Data frames
Int <- c(1:5); Char <- letters[1:5]; 
Log <- c(T,F,F,T,F); Comp <- c(1i,1+2i,5,8i,4)
data.frame(Int,Char,Log,Comp)

Int Char Log   Comp
1 1   a     TRUE 0+1i
2 2   b    FALSE 1+2i
3 3   c    FALSE 5+0i
4 4   d     TRUE 0+8i
5 5   e    FALSE 4+0i

In [28]:
## List
(list1 <- list(age = c(1:5), #numeric vector
                          name = c("John","Neil","Lisa","Jane"), #character vector 
                          mat = matrix(1:9,nrow = 3), #numeric matrix
                          df = data.frame(name = c("John","Neil","Lisa","Jane"), gender = c("M","M","F","F")), #data frame
                          small_list = list(city = c("Texas","New Delhi","London"), country = c("USA","INDIA","UK")))) #list

$age
[1] 1 2 3 4 5

$name
[1] "John" "Neil" "Lisa" "Jane"

$mat
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$df
  name gender
1 John      M
2 Neil      M
3 Lisa      F
4 Jane      F

$small_list
$small_list$city
[1] "Texas"     "New Delhi" "London"   

$small_list$country
[1] "USA"   "INDIA" "UK"

In [29]:
elist <- list(vec=1:4,df=data.frame(a=1:3, b=4:6),mat=matrix(1:4, nrow=2), name="pks")

In [30]:
elist[["vec"]]

[1] 1 2 3 4

In [31]:
elist

$vec
[1] 1 2 3 4

$df
  a b
1 1 4
2 2 5
3 3 6

$mat
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$name
[1] "pks"

##### Linear Linked List

In [32]:
# empty linked list

create_emptyenv <- function() {
  emptyenv()
}

In [33]:
# check is list is empty

isEmpty <- function(llist) {
  if(class(llist)!= "linkList") warning("Not linkList class")
  identical(llist, create_emptyenv())
}

In [34]:
# define a linked list

linkListNode <- function(val, node=NULL) {
  llist <- new.env(parent=create_emptyenv())
  llist$element <- val
  llist$nextnode <- node
  class(llist) <- "linkList"
  llist
}

In [35]:
# create a link list

LList <-linkListNode(5,linkListNode(2,create_emptyenv()))

In [36]:
# add nodes

setNextNode<-function(llist){
  llist$nextnode
}
setNextElement<-function(llist){
  llist$element
}

In [37]:
# return size of linked list

sizeLinkList<-function(llist, size=0){
  if (isEmpty(llist)) 
  {
    return(size)
  } else
  {
    size<-size+1L
    sizeLinkList(llist$nextnode, size)
  }
}

In [38]:
# insertion

addElement<-function(new, llist) 
{
  if (isEmpty(llist)) {
    llist<-linkedlist(new)
  } else
  {
    llist<-linkListNode(llist, new)
  }
  llist
}

In [39]:
# delete and update links

delElement<-function(llist, pos=NULL){
  if(is.null(pos)) warning("Nothing to delete")
  listsize<-sizeLinkList(llist)
  if(pos>listsize) stop("Position greater than size of list")
  if (isEmpty(llist)) {
    warning("Empty List")
  } else if(pos==1){
    PreviousNode<-llist$nextnode
  } else 
  {
    PreviousNode<-linkListNode(llist$element)
    for(i in 1:(listsize-1)){
      if(pos==(i+1)){
        PreviousNode$nextnode<-setNextNode(llist$nextnode)
      } else
      {
        PreviousNode$nextnode<-llist$nextnode
        llist<-llist$nextnode
      }
    }
  }
  return(PreviousNode)
}

In [40]:
# searching

findItem<-function(llist, item, pos=0, itemFound=FALSE){
  if (itemFound==TRUE) 
  {
    return(itemFound)
  } else if(isEmpty(llist)){
    return(FALSE)
  } else
  {
    pos<-pos+1L
    if(llist$element==item) itemFound<-TRUE
    findItem(llist$nextnode, item, size, itemFound)
  }
}

##### Doubly linked list

In [41]:
dlinkListNode <- function(val, prevnode=NULL, node=NULL) {
  llist <- new.env(parent=create_emptyenv())
  llist$prevnode <- prevnode
  llist$element <- val
  llist$nextnode <- node
  class(llist) <- "dlinkList"
  llist
}

##### Circular linked list

In [42]:
cicularLinkList<-function(llist, val){
  if(isEmpty(llist)){
    llist<-linkListNode(val)
    head<-llist
  } else
  {
    llistNew<-linkListNode(val)
    llistNew$nextnode<-head
    llist<-linkListNode(llist, llistNew) 
  }
  llist
}

##### Array list

In [43]:
ALinkList<-setRefClass(Class = "ALinkList",
                       fields = list(
                         Alist="array",
                         listsize="integer",
                         arraySize="integer",
                         maxSize="integer"
                       ), 
                       methods = list(
                         initialize=function(...){
                           listsize<<-0L
                           arraySize<<-100L
                           Alist<<-array(dim = arraySize)
                           maxSize<<-arraySize
                         }
                       ))

In [44]:
# return lenght of array

listlen = function()
{
  return(listsize)
}

In [45]:
# update array size as needed

updateArrayList=function(){
  Alist<<-c(Alist, array(dim=arraySize))
  maxSize<<-maxSize+arraySize
}

addItem=function(item){
  if(maxSize<=listsize){
    updateArrayList()
  } 
  listsize<<-listsize+1L
  Alist[listsize]<-item
  return(listsize)
}

In [46]:
# remove item based on index

removeItem = function(i)
{
  Alist[i] <<- NULL
  listsize <<- listsize - 1L
}

In [47]:
# searching 

searchItem = function(val){
  pointer<-1L
  while(pointer!=listsize){
    if(Alist[pointer]==val){
      break
    } 
    pointer<-pointer+1L
  }
  return(pointer)
}